### ISSUE TITLE
Doesn’t work with VH 3.16

### ISSUE THREAD

**Issue by alterNERDtive** [radimous/BetterBountyTable#1]
Goold old

> net.minecraftforge.fml.ModLoadingException: The Vault (the_vault) encountered an error during the common_setup event phase
> §7org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered […]

**Comment by radimous** [comment]
why would you need it in 3.16?
everything should be in the base mod now
reroll focus has been in vanilla since U13, rendering perf improvements and tooltip hiding when holding shift was added in U16

**Comment by alterNERDtive** [comment]
Ah. Haven’t played in ages, so didn’t know. And it’s not like the pack’s patch notes are helpful :)
